### ISSUE TITLE
Application CICD

### ISSUE THREAD

**Issue by kikobr82** [devopsacademyau/2020-jun-project1-group1#12]
**Objectives:**
- [x] Create a workflow in GitHub Actions to build and push the image on every update in the application folder(PRs)
- [x] Create a workflow in GitHub Actions to deploy the new image when new application code is merged into master

**Acceptance:**
- [x] Workflow must use the same targets created on #11
- [x] Workflows are running successfully and the application is being updated from events in GH

**Comment by alanlima** [comment]
The objectives are addressed in PR #32 
But the acceptance criteria **still pending** until the other task are finished
